#!/usr/bin/env python
import sys

from parquet2hive_modules import parquet2hivelib as lib

if __name__ == "__main__":
    errored, result = lib.run(sys.argv[1:])

    print result
    if errored != 0:
        exit(errored)
